### ISSUE TITLE
Removed swagger.json causes problem with SDK generator wiki

### ISSUE THREAD

**Issue by PoOwAa** [samchon/nestia-template#3]
At https://github.com/samchon/nestia/wiki/SDK-Generator#swagger-documents, there's a table that displays an example Swagger page generated by Nestia. The Swagger editor page for this project dynamically loads the swagger.json file from the following URL: https://raw.githubusercontent.com/samchon/nestia-template/master/dist/swagger.json.

However, after commit 9d4bc0c907d790ff416f46853400d2e0e1cfea51, the swagger.json file was removed from the master branch, causing the Swagger editor page to fail to load it. As this is a template project, it's unclear why the file was removed. Could you please provide more information on the reason behind the removal of the swagger.json file?

Here is the broken editor:
[Swagger Editor](https://editor.swagger.io/?url=https://raw.githubusercontent.com/samchon/nestia-template/master/dist/swagger.json)

Here is a working editor with the previous commit:
[Working Swagger Editor](https://editor.swagger.io/?url=https://raw.githubusercontent.com/samchon/nestia-template/ab0bdce89b19c70f069bb1ec35e11edd0eb93384/dist/swagger.json)

**Comment by samchon** [comment]
Revived it, thx for reporting.
